Chanakya/redeem dust value
interlay/polkabtc-ui pull request #219
Opened 2021-04-27 10:28 UTC by Chanakya888

2021-04-27 10:42 UTC, nud3l requested changes

2021-04-27 10:42 UTC, nud3l commented on src/pages/Application/redeem/enter-amount-and-address.tsx
> +      toast.warning(t('redeem_page.amount_greater') + dustValue + 'BTC)');
This error message should be displayed below the input form just like on redeem. Not a toast.

Also, the amount should not be set if it fails the validation, e.g. the `setAmmountPolkaBTC` should not be called.

2021-04-27 10:47 UTC, nud3l commented on src/pages/Application/redeem/enter-amount-and-address.tsx
> +      toast.warning(t('redeem_page.amount_greater') + dustValue + 'BTC)');
@anton-karlovskiy I think we could also have a general "input validation" function that is applicable for both issue and redeem. We have several checks in common like:

Input amount
- dust value check

State of the app
- parachainStatus is Running
- address is set
- bitcoin height (e.g. https://github.com/interlay/polkabtc-ui/blob/dev/src/pages/Application/issue/enter-btc-amount.tsx#L221 and https://github.com/interlay/polkabtc-ui/blob/dev/src/pages/Application/redeem/enter-amount-and-address.tsx#L138)

2021-04-27 10:52 UTC, Chanakya888 commented on src/pages/Application/redeem/enter-amount-and-address.tsx
> +      toast.warning(t('redeem_page.amount_greater') + dustValue + 'BTC)');
1. Okay, I'll add the error message below the field.
2.  for clarification, my assumption of `disallow` in the ticket meant the user shouldn't be allowed to enter an amount that is less than the `dust value` which is what I tried to do here, whenever a user enters a value that is less than dust value, the value itself changes to 0 and throws in error, am I in the right direction here?

2021-04-27 13:19 UTC, nud3l commented on src/pages/Application/redeem/enter-amount-and-address.tsx
> +      toast.warning(t('redeem_page.amount_greater') + dustValue + 'BTC)');
Yep, the code to display error messages below the input field is already there so should hopefully be easy to add.

If the user enters an amount below the dust value, the error field below the input field is displayed and the value changes to `undefined`

2021-04-27 13:48 UTC, Chanakya888 commented on src/pages/Application/redeem/enter-amount-and-address.tsx
> +      toast.warning(t('redeem_page.amount_greater') + dustValue + 'BTC)');
wait a sec, sorry (I'm a bit confused as I am not able to test it). You'd want the input field value to change to `0.00` (not `undefined`) if value < dustValue

2021-04-27 14:03 UTC, nud3l commented on src/pages/Application/redeem/enter-amount-and-address.tsx
> +      toast.warning(t('redeem_page.amount_greater') + dustValue + 'BTC)');
The input field itself should stay at whatever was just entered by the user. The amount itself should be undefined.

Please have a look how this is done in issue. We don't need to introduce any booleans component level variables for this: https://github.com/interlay/polkabtc-ui/blob/dev/src/pages/Application/issue/enter-btc-amount.tsx#L279

2021-04-28 09:32 UTC, Chanakya888 commented
@nud3l Closing this PR confirmed with Dan that he wanted a check onSubmit, @anton-karlovskiy says he will give real time validation a try during his refactoring.

2021-04-28 09:32 UTC, closed without merging