Chanakya/add account name
interlay/polkabtc-ui pull request #222
Opened 2021-05-04 07:24 UTC by Chanakya888

2021-05-04 12:32 UTC, nud3l reviewed
I think it would be helpful to have a design for this. The functional requirement to add the account name Is there, but it does not look very pretty.

The selected looks exactly like the account name:

![image](https://user-images.githubusercontent.com/14966470/117003493-e2776900-ad1f-11eb-892d-42d2e2759a6b.png)

Maybe one way to improve would be to have:

dom0 (5...)     :white_check_mark: 
beta-sudo (5...)
beta-vault-0 (5....)

The checkmark can be on the right hand side (right aligned)

As an addition, we can also have dedicated icons for vaults and relayers and show those on the right side of the account to indicate that those are registered as vaults/relayers.

2021-05-04 12:32 UTC, nud3l commented on src/common/components/account-modal/account-modal.tsx
> +  accountNames:string[]
```suggestion
  accountNames: string[]
```

2021-05-04 12:57 UTC, Chanakya888 commented on src/common/components/account-modal/account-modal.tsx
> +  accountNames:string[]
Agreed, I gotta update the design for this, do you want me to do this in this PR? or create a new one later?

Also quick question, I know you suggested names in modal only, but do you think having the name even in the top bar makes sense? for example Acala (https://apps.acala.network/)

2021-05-04 14:13 UTC, nud3l commented on src/common/components/account-modal/account-modal.tsx
> +  accountNames:string[]
Yes, I think having it in the top bar would be great!

2021-05-04 14:14 UTC, nud3l commented on src/common/components/account-modal/account-modal.tsx
> +  accountNames:string[]
> Agreed, I gotta update the design for this, do you want me to do this in this PR? or create a new one later?

let's do that in this PR

2021-05-05 09:29 UTC, anton-karlovskiy commented
@Chanakya888 cc @nud3l 
Could you please let me know once you've finished? I'd like to have a look at the changes.

2021-05-05 18:33 UTC, anton-karlovskiy commented on package.json
> -    "node-sass": "^4.14.1",
@Chanakya888 
It's dropped again.

2021-05-05 18:37 UTC, Chanakya888 commented
> @Chanakya888 cc @nud3l
> Could you please let me know once you've finished? I'd like to have a look at the changes.

Yes Definitely

2021-05-05 18:39 UTC, Chanakya888 commented on package.json
> -    "node-sass": "^4.14.1",
Yup, I'll add it back in my final commit.

**Context:**
For some reason if "node-sass" is present in my package.json, my local build fails. I tried to debug but was unsuccessful so I am using this hack of removing it at the start of PR and adding it back once I am done with the PR

2021-05-05 21:12 UTC, anton-karlovskiy commented on package.json
> -    "node-sass": "^4.14.1",
@Chanakya888 
Without it, I'm not able to run locally.

2021-05-06 04:24 UTC, Chanakya888 commented on package.json
> -    "node-sass": "^4.14.1",
Please add it back and run locally

2021-05-06 06:30 UTC, Chanakya888 commented
@nud3l @anton-karlovskiy 
Please have a look at the PR now.
1. I've tested it to make sure it doesn't break the app if there's something wrong with name
2. @nud3l I've added a green circle on the left to indicate that this account is currently selected and active, my thought is to have the vault and relayer text and icons (wherever applicable) right side of the text. Please let me know what you think about this choice 
3. I've also reduced the contrast as I felt pink is too much, reduced it down to reasonable grey

2021-05-06 07:49 UTC, anton-karlovskiy commented
@Chanakya888 @nud3l 
FYI: let me have a look.

2021-05-06 17:30 UTC, anton-karlovskiy commented on src/App.tsx
> +      console.log('account details', accountDetails);
@Chanakya888 
Should remove console logs.

2021-05-06 17:32 UTC, Chanakya888 commented on src/App.tsx
> +      console.log('account details', accountDetails);
Whoops, sorry

2021-05-06 17:59 UTC, anton-karlovskiy commented on src/common/components/account-modal/account-modal.tsx
> +  console.log('Accounts are ', accountDetails);
@Chanakya888 
Here

2021-05-06 18:01 UTC, anton-karlovskiy commented on src/common/components/account-modal/account-modal.tsx
> +                  key={index}
@Chanakya888 
Should not use `index` as a key. It's sort of an anti-pattern in React.

2021-05-06 22:01 UTC, anton-karlovskiy commented on src/common/components/account-modal/account-modal.tsx
> +                      selectedAccount === details.accountAddress ? 'bg-green-500' : 'bg-white-100')}>
@Chanakya888 
We can use `bg-transparent` rather than `bg-white-100` as we might want to use dark mode in the future.

2021-05-07 04:24 UTC, Chanakya888 commented on src/common/components/account-modal/account-modal.tsx
> +                      selectedAccount === details.accountAddress ? 'bg-green-500' : 'bg-white-100')}>
@anton-karlovskiy Shall I push a commit with these changes? or are you working on something in this PR?

2021-05-07 05:14 UTC, anton-karlovskiy commented on src/common/components/account-modal/account-modal.tsx
> +                      selectedAccount === details.accountAddress ? 'bg-green-500' : 'bg-white-100')}>
Please do not push changes for a while.

2021-05-07 07:25 UTC, anton-karlovskiy commented on src/common/components/topbar.tsx
> +    });
@Chanakya888 
We can use `.find` method rather than iterating.

2021-05-07 10:28 UTC, Chanakya888 commented on src/common/components/topbar.tsx
> +    });
Yeah, should've done that. Please leave these changes to me, I'll get them done once you are done making your changes

2021-05-07 10:32 UTC, anton-karlovskiy commented on src/common/components/topbar.tsx
> +    });
@Chanakya888 
Hmm, I'm afraid, relatively a lot of changes are expected including the app initialization.

2021-05-10 07:35 UTC, nud3l requested changes
When you don't have the extension installed, it should show "Connect Wallet" on the account button on the right side button in the topbar, but it is empty:

![image](https://user-images.githubusercontent.com/14966470/117622252-69f42a80-b1ad-11eb-9ca2-67bd8cc4484c.png)

Also, when you don't expose any of your accounts, the button should say "Select Account", but it is also empty:

![image](https://user-images.githubusercontent.com/14966470/117622446-9a3bc900-b1ad-11eb-8eca-ec49db1feb1f.png)


I like the Green online thing and the more subtle grey selection :)

2021-05-10 09:02 UTC, Chanakya888 commented
> When you don't have the extension installed, it should show "Connect Wallet" on the account button on the right side button in the topbar, but it is empty:
> 
> ![image](https://user-images.githubusercontent.com/14966470/117622252-69f42a80-b1ad-11eb-9ca2-67bd8cc4484c.png)
> 
> Also, when you don't expose any of your accounts, the button should say "Select Account", but it is also empty:
> 
> ![image](https://user-images.githubusercontent.com/14966470/117622446-9a3bc900-b1ad-11eb-8eca-ec49db1feb1f.png)
> 
> I like the Green online thing and the more subtle grey selection :)

Whaat, that's weird. I am sure they were working when I tested, I am assuming they were lost during the refactor, @anton-karlovskiy please have a look.

2021-05-11 17:12 UTC, merged